instruments:
  - type: numeric_display
    gang_type: horizontal
    row: 0
    column: 0
    span:
      rows: 8
      columns: 30
    options:
      #font_ghost_mask: "~~~~~~~"
      #font_family: "DSEG14 Classic"
      font_mask: "000.000"
      decimal_places: 3
      dbkey: COMACTFREQ{radio_id}
      encoder_order: 24
  - type: value_text
    row: 8
    column: 0
    span:
      rows: 5
      columns: 35
    options:
      #font_family: "DSEG14 Classic"
      #font_ghost_mask: "~~~~~~~~~~~~~"
      font_mask:       "XXXXXXXXXXXXX"
      _dbkey: COMACTNAME{radio_id}
  - type: button
    row: 14
    column: 0
    span:
      rows: 6
      columns: 6
    options:
      config: buttons/mgl/v16/active-rx-status.yaml
  - type: horizontal_bar_gauge
    ratio: 3
    row: 13
    column: 7
    span:
      rows: 8
      columns: 24
    options:
      name: RX
      bar_divisor: 2.5
      decimapPlaces: 0
      show_units: false
      show_value: false
      dbkey: COMACTRXLEVEL{radio_id}
      segments: 22
  - type: horizontal_bar_gauge
    ratio: 3
    row: 16.5
    column: 7
    span:
      rows: 8
      columns: 24
    options:
      name: Squelch
      encoder_order: 25
      bar_divisor: 2.5
      decimapPlaces: 0
      show_units: false
      show_value: false
      dbkey: COMSQUELCH{radio_id}
      segments: 22
  - type: button
    row: 21.5
    column: 0
    span:
      rows: 6
      columns: 6
    options:
      config: buttons/mgl/v16/active-tx-status.yaml
  - type: horizontal_bar_gauge
    ratio: 3
    row: 20
    column: 7
    span:
      rows: 8
      columns: 24
    options:
      name: TX
      bar_divisor: 2.5
      decimapPlaces: 0
      show_units: false
      show_value: false
      dbkey: COMTXPWR{radio_id}
      segments: 22
  - type: horizontal_bar_gauge
    ratio: 3
    row: 23.5
    column: 7
    span:
      rows: 8
      columns: 24
    options:
      name: SWR
      bar_divisor: 2.5
      decimapPlaces: 0
      show_units: false
      show_value: false
      dbkey: COMVSWR{radio_id}
      segments: 22
