instruments:
  - type: numeric_display
    gang_type: horizontal
    row: 0
    column: 0
    span:
      rows: 8
      columns: 30
    options:
      decimalPlaces: 3
      dbkey: COMACTFREQ{radio_id}
  - type: value_text
    row: 8
    column: 0
    span:
      rows: 5
      columns: 35
    options:
      _dbkey: COMACTNAME{radio_id}
  - type: button
    row: 14
    column: 0
    span:
      rows: 5
      columns: 5
    options:
      config: buttons/mgl/v16/active-rx-status.yaml
  - type: horizontal_bar_gauge
    ratio: 3
    row: 13
    column: 6
    span:
      rows: 8
      columns: 24
    options:
      name: RX
      decimapPlaces: 0
      showUnits: false
      showValue: false
      dbkey: COMACTRXLEVEL{radio_id}
  - type: horizontal_bar_gauge
    ratio: 3
    row: 16.5
    column: 6
    span:
      rows: 8
      columns: 24
    options:
      name: Squelch
      decimapPlaces: 0
      showUnits: false
      showValue: false
      dbkey: COMSQUELCH{radio_id}
  - type: button
    row: 20
    column: 0
    span:
      rows: 5
      columns: 5
    options:
      config: buttons/mgl/v16/active-tx-status.yaml
  - type: horizontal_bar_gauge
    ratio: 3
    row: 20
    column: 6
    span:
      rows: 8
      columns: 24
    options:
      name: TX
      decimapPlaces: 0
      showUnits: false
      showValue: false
      dbkey: COMTXPWR{radio_id}
  - type: horizontal_bar_gauge
    ratio: 3
    row: 23.5
    column: 6
    span:
      rows: 8
      columns: 24
    options:
      name: SWR
      decimapPlaces: 0
      showUnits: false
      showValue: false
      dbkey: COMVSWR{radio_id}

