instruments:
  - type: numeric_display
    gang_type: horizontal
    row: 0
    column: 0
    span:
      rows: 8
      columns: 30
    options:
      #font_ghost_mask: "~~~~~~~"
      #font_family: "DSEG14 Classic"
      font_mask: "100.000"
      decimalPlaces: 3
      dbkey: COMSTDFREQ{radio_id}
  - type: value_text
    row: 8
    column: 0
    span:
      rows: 5
      columns: 35
    options:
      #font_family: "DSEG14 Classic"
      #font_ghost_mask: "~~~~~~~~~~~~~"
      font_mask:       "XXXXXXXXXXXXX"
      _dbkey: COMSTDNAME{radio_id}
  - type: button
    row: 14
    column: 0
    span:
      rows: 6
      columns: 6
    options:
      config: buttons/mgl/v16/standby-rx-status.yaml
  - type: horizontal_bar_gauge
    ratio: 3
    row: 13
    column: 7
    span:
      rows: 8
      columns: 24
    options:
      name: RX
      bar_divisor: 2.5
      decimapPlaces: 0
      showUnits: false
      showValue: false
      dbkey: COMSTDRXLEVEL{radio_id}
      segments: 22
