instruments:
  - type: ganged_vertical_bar_gauge
    gang_type: horizontal
    ratio: 0.2
    row: 1.5
    column: 0
    span:
      rows: 36
      columns: 30
    groups:
      - name: Volume
        gap: 0
        common_options:
          show_value: false
          show_units: false
          small_font_percent: 0.060
          big_font_percent: 0.085
          bar_width_percent: 0.5
          line_width_percent: 0.7
          text_gap: 8
          segments: 22
        instruments:
          -
            options:
              name: "RX Vol"
              decimal_places: 0
              dbkey: COMRXVOL{radio_id}
              encoder_order: 21
          -
            options:
              name: "Int Vol"
              decimal_places: 0
              dbkey: COMINTVOL{radio_id}
              encoder_order: 22
          -
            options:
              name: "Aux Vol"
              decimal_places: 0
              dbkey: COMAUDVOL{radio_id}
              encoder_order: 23
# Aux Volume might not exist
# The intention was to show volume for the audio input
