type: toggle
text: "Fight\nPlan"
dbkey: BTNFP
condition_keys:
  - BTNAP
#  - BTNHH
  - APMODE
  - APSTAT
  - APREQ
  - WPLAT
  - WPLON
conditions:
  - when: "WPLAT.old eq true or WPLON.old eq true or APSTAT ne 'ARMED'"
    # When any condition would prevent use of this mode disable the button
    # This will prevent eval of any other conditions
    actions:
      - button: unchecked
      - button: disable
      - set bg color: red
  - when: "APMODE ne 'GUIDED' and WPLAT.old ne true and WPLON.old ne true"
    actions:
      - button: enable
    continue: true
  - when: "APMODE ne 'GUIDED' and APREQ ne 'GUIDED'"
    actions:
      - set bg color: lightgray
    continue: true
  - when: "CLICKED eq true and BTNFP eq false and APMODE eq 'GUIDED' and APREQ eq 'GUIDED'"
    actions:
      - set value: APREQ, TRIM
      - set bg color: orange
  - when: "CLICKED eq true and BTNFP eq true and APMODE ne 'GUIDED'"
    actions:
      - set value: APREQ, GUIDED
#      - set value: BTNHH, False
      - set bg color: orange
  - when: "CLICKED eq false and APMODE eq 'GUIDED' and [ APREQ eq 'GUIDED' or APREQ eq 'INIT']"
    actions:
      - set bg color: green
      - button: checked
#      - set value: BTNHH, False



