type: toggle
text: "Auto Pilot\n"
dbkey: BTNAP
condition_keys:
  - APSTAT
  - APMSG
  - APMODE
  - APREQ
conditions:
  - when: "APSTAT ne 'ARMED'"
    actions:
      - button: disable
      - set text: "Auto Pilot\n{APMSG}"
      - set value: BTNAP, False
      - set bg color: red
    continue: true
  - when: "APSTAT eq 'ARMED'"
    actions:
      - button: enable
      - set text: "Auto Pilot\n{APMSG}"
      #- set value: BTNAP, False
      - set bg color: lightgrey
    continue: true
  - when: "APSTAT eq 'ARMED' and BTNAP eq true"
    actions:
      - set text: "Auto Pilot\n{APMSG}"
      - set bg color: green
      #- set value: BTNAP, True
  - when: "CLICKED eq true and APSTAT eq 'ARMED' and BTNAP eq true"
    actions:
      - set text: "Auto Pilot\n{APMSG}"
      - set bg color: lightgray
      - set value: APREQ, TRIM
