type: toggle
text: "Normalize\n "
dbkey: EGTBTN2
conditions:
  - when: "CLICKED eq true and EGTBTN2 eq true"
    actions:
      - set value: EGTBTN3, False #Turn off EGT Peak button
      - set value: EGTBTN4, False #Turn off EGT Lean button
      - set egt mode: normal
      - Set EGT Mode: Normalize
      - set bg color: green
  - when: "CLICKED eq true and EGTBTN2 eq false"
    actions:
      - set EGT Mode: normal
      - set bg color: lightgray
