type: simple
text: ""
dbkey: BTN6
conditions:
  - when: "SCREEN eq 'EMS'"
    actions:
      - set text: PFD
    continue: true
  - when: "SCREEN eq 'PFD'"
    actions:
      - set text: EMS
    continue: true
  - when: "CLICKED eq true and SCREEN eq 'PFD'" 
    actions:
      - show screen: EMS
  - when: "CLICKED eq true and SCREEN eq 'EMS'"
    actions:
      - show screen: PFD

