type: simple
text: ""
dbkey: TSBTN{id}12
condition_keys:
  - CHT11
  - CHT12
  - CHT13
  - CHT14
  - EGT11
  - EGT12
  - EGT13
  - EGT14
conditions:
  - when: "SCREEN eq 'EMS'"
    actions:
      - set text: PFD
      - set bg color: lightgray
    continue: true
  - when: "SCREEN eq 'PFD' or SCREEN eq 'MAP'"
    actions:
      - set text: EMS
      - set bg color: lightgray
    continue: true
  - when: "SCREEN ne 'EMS' and [ CHT11.annunciate or CHT12.annunciate or CHT13.annunciate or CHT14.annunciate or EGT11.annunciate or EGT12.annunciate or EGT13.annunciate or EGT14.annunciate ]"
    actions:
      - set bg color: red
    continue: true
  - when: "CLICKED eq true and [ [ SCREEN eq 'PFD' ] or [ SCREEN eq 'MAP' ] ]" 
    actions:
      - show screen: EMS
  - when: "CLICKED eq true and SCREEN eq 'EMS'"
    actions:
      - show screen: PFD

