type: simple
text: "RX"
dbkey: TSBTN{id}18
condition_keys:
  - COMSTDRX1
conditions:
  - when: "COMSTDRX1 eq true"
    actions:
      - button: disable
      - set bg color: green
  - when: "COMSTDRX1 eq false"
    actions:
      - button: disable
      - set bg color: white

