instruments:
  - type: ganged_vertical_bar_gauge
    gang_type: horizontal
    ratio: 0.2
    row: 0
    column: 0
    span:
      rows: 40
      columns: 80
    groups:
      - name: RPM
        gap: 0
        common_options:
          segments: 22
          show_units: false
          small_font_percent: 0.060
          big_font_percent: 0.085
          bar_width_percent: 0.5
          line_width_percent: 0.7
          text_gap: 8
        instruments:

          -
            options:
              name: RPM
              decimal_places: 0
              dbkey: TACH1
          -
            options:
              name: TPS
              decimal_places: 2
              dbkey: THR1
              show_units: True
      - name: Engine
        gap: 0
        common_options:
          segments: 22
          small_font_percent: 0.060
          big_font_percent: 0.085
          bar_width_percent: 0.5
          line_width_percent: 0.7
          text_gap: 8
          show_units: False
        instruments:
          -
            options:
              name: MAP
              decimal_places: 0
              dbkey: MAP1
          -
            options:
              name: IT
              decimal_places: 0
              dbkey: MAP1
          -
            options:
              name: AFR
              decimal_places: 0
              dbkey: MAP1
          -
            options:
              name: AFRT
              decimal_places: 0
              dbkey: MAP1
          -
            options:
              name: EGO
              decimal_places: 0
              dbkey: MAP1
      - name: Temps
        gap: 0
        common_options:
          segments: 22
          small_font_percent: 0.060
          big_font_percent: 0.085
          bar_width_percent: 0.5
          line_width_percent: 0.7
          text_gap: 8
        instruments:
          -
            options:
              name: IAT
              decimal_places: 0
              dbkey: CAT
              temperature: true

