instruments:
  - type: ganged_arc_gauge
    gang_type: vertical
    row: 0
    column: 0
    span:
      rows: 70
      columns: 30
    groups:
      - name: Power and Temp
        common_options:
          name_location: right
          decimal_places: 0
          segments: 28
        instruments:
          -
            options:
              name: Volts
              dbkey: VOLT
              decimal_places: 1
          -
            options:
              name: Amps
              dbkey: CURRNT
              decimal_places: 1
          -
            options:
              name: OAT
              dbkey: OAT
              temperature: true
              show_units: true
          -
            options:
              name: CAT
              temperature: true
              dbkey: CAT
              show_units: true

