instruments:
  - type: ganged_button
    gang_type: vertical
    row: 0
    column: 0
    span:
      rows: 110
      columns: 14.5
    groups:
      - name: Side Buttons
        gap: 11
        instruments:
          -
            options:
              config: buttons/screen-ems-pfd.yaml
          -
            options:
              config: buttons/screen-map-pfd.yaml
          -
            options:
              config: buttons/units.yaml
          -
            options:
              config: buttons/auto-pilot-adjust.yaml
          -
            options:
              config: buttons/auto-pilot-heading-hold.yaml
          -
            options:
              config: buttons/auto-pilot-flight-plan.yaml
