# Data Computation
compute:
  load: COMPUTE
  module: fixgw.plugins.compute
  functions:
    - function: average
      inputs: ["EGT11", "EGT12", "EGT13", "EGT14"]
      output: EGTAVG1
    - function: span
      inputs: ["EGT11", "EGT12", "EGT13", "EGT14"]
      output: EGTSPAN1
    - function: max
      inputs: ["EGT11", "EGT12", "EGT13", "EGT14"]
      output: EGTMAX1
    - function: max
      inputs: ["CHT11", "CHT12", "CHT13", "CHT14"]
      output: CHTMAX1
    - function: sum
      inputs: ["FUELQ1", "FUELQ2", "FUELQ3"]
      output: FUELQT
    - function: altp
      inputs: ["BARO", "TALT"]
      output: PALT
    - function: altd
      inputs: ["PALT","TALT","OAT"]
      output: DALT
    #   inputs: []
    #   output: x
    # - function: span
    #   inputs: []
    #   output: x
    # - function: TAS
    # - function: DALT
# BARO Encoder
      - function: encoder
        inputs: [ "ENC1" ]
        output: BARO
        multiplier: 0.01
# BARO set to 29.92
      - function: set
        inputs: [ "BTN1" ]
        value: 29.92
        output: BARO
# TRIMP Encoder
      - function: encoder
        inputs: [ "ENC2" ]
        output: TRIMP
        multiplier: 0.1
# TRIMP Center
      - function: set
        inputs: [ "BTN2" ]
        value: 0
        output: TRIMP
# TRIMR Encoder
      - function: encoder
        inputs: [ "ENC3" ]
        output: TRIMR
        multiplier: 0.1
# TRIMR Center
      - function: set
        inputs: [ "BTN3" ]
        value: 0
        output: TRIMR

# TRIMY Encoder
      - function: encoder
        inputs: [ "ENC4" ]
        output: TRIMY
        multiplier: 0.1
# TRIMY Center
      - function: set
        inputs: [ "BTN4" ]
        value: 0
        output: TRIMY

