mavlink:
  load: MAVLINK
  module: fixgw.plugins.mavlink
  type: serial
  baud: 115200
  port: /dev/ttyUSB0
  options:
    airspeed: true
    groundspeed: true
    gps: true
    ahrs: true
    accel: true
    pressure: true
    pascal_offset: 2800

